name: Build
on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:

          - job_name: lint
            run_script: bun run lint

          - job_name: format
            run_script: bun run format:check

          - job_name: build
            run_script: |
              bun run ts:build

          - job_name: lint-deps
            run_script: bun run lint:deps

          - job_name: test
            run_script: |
                bun run test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3
      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Run ${{ matrix.job_name }}
        run: ${{ matrix.run_script }}
