name: Publish

on:
  push:
    tags:
      - '**'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - uses: oven-sh/setup-bun@v2
      - name: Install deps
        run: |
          bun --version
          bun install --frozen-lockfile

      - name: Extract version
        id: versions
        uses: ./.github/actions/extract-version
        with:
          version: ${{ github.ref }}

      - name: "Build app"
        run: bun run build

      - name: "Publish NPM"
        run: bash ./scripts/npm-publish/run.sh
        env:
          NPM_TAG: ${{ steps.versions.outputs.npmTag }}

      - name: "Dump npm logs on failure"
        if: failure()
        run: |
          echo "=== NPM Debug Logs ==="
          find /home/runner/.npm/_logs -name "*.log" -type f -exec echo "=== {} ===" \; -exec cat {} \;
