name: Publish
on:
  push:
    tags:
      - '**'
permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.9
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install deps
        run: |
          bun --version
          bun install --frozen-lockfile

      - name: Extract version
        id: versions
        uses: ./.github/actions/extract-version
        with:
          version: ${{ github.ref }}

      - name: Build app
        run: bun run build

      - name: Publish
        run: bun publish
